{
  imports = [
    ./any-nix-shell.nix
    ./bat.nix
    ./comma.nix
    ./dircolors.nix
    ./direnv.nix
    ./exa.nix
    ./fd.nix
    ./fish.nix
    ./fzf.nix
    ./git-fast-forward-all.nix
    ./git.nix
    ./janus.nix
    ./less.nix
    ./neovim
    ./nix.nix
    ./ripgrep.nix
    ./some.nix
    ./starship.nix
  ];
}
