{
  imports = [
    ./7zip.nix
    ./bash.nix
    ./bat.nix
    ./binary-ninja
    ./bintools.nix
    ./brightnessctl.nix
    ./calculator.nix
    ./calibre.nix
    ./colordiff.nix
    ./comma.nix
    ./dconf-editor.nix
    ./dig.nix
    ./dircolors.nix
    ./direnv.nix
    ./discord.nix
    ./display-volume.nix
    ./dunst.nix
    ./eiciel.nix
    ./element.nix
    ./evince.nix
    ./exiftool.nix
    ./fd.nix
    ./ffmpeg.nix
    ./file2img
    ./firefox.nix
    ./flac.nix
    ./flameshot.nix
    ./frescobaldi.nix
    ./gammastep.nix
    ./gdb.nix
    ./glimmer
    ./gnome-music.nix
    ./gpg.nix
    ./hexchat
    ./htop.nix
    ./httpie.nix
    ./hushboard.nix
    ./i3
    ./inkscape.nix
    ./insync.nix
    ./jetbrains.nix
    ./jless.nix
    ./jq.nix
    ./kdeconnect.nix
    ./kdenlive.nix
    ./keepassxc.nix
    ./keychain.nix
    ./kid3.nix
    ./kitty
    ./libreoffice.nix
    ./lorri.nix
    ./lsof.nix
    ./lutris.nix
    ./lyx.nix
    ./make.nix
    ./mpv.nix
    ./nemo.nix
    ./nix-locate.nix
    ./nix-prefetch.nix
    ./nix-script.nix
    ./nix.nix
    ./notify-send.nix
    ./obs.nix
    ./obsidian.nix
    ./peek.nix
    ./playerctl.nix
    ./pngcrush.nix
    ./polymc.nix
    ./qpwgraph.nix
    ./qutebrowser.nix
    ./rcu
    ./readline.nix
    ./rhythmbox.nix
    ./rink.nix
    ./rustup.nix
    ./signal.nix
    ./slack.nix
    ./sqlitebrowser.nix
    ./ssh.nix
    ./steam.nix
    ./sublime-merge.nix
    ./syncthing.nix
    ./systemd.nix
    ./talon
    ./tenacity.nix
    ./thunar.nix
    ./tio.nix
    ./todoist.nix
    ./tradedangerous.nix
    ./unicode.nix
    ./vim
    ./whois.nix
    ./wine.nix
    ./wxhexeditor.nix
    ./xclip.nix
    ./xivlauncher.nix
    ./xorg
    ./youtube-dl.nix
    ./zenity.nix
    ./zip.nix
    ./zoom.nix
    ./zotero.nix
    ./zulip.nix
  ];
}
